django_project/blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.flatpages import views as flat_views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    url(r'^about/$', flat_views.flatpage, {'url': '/about/'}, name='about'),
    url(r'^eula/$', flat_views.flatpage, {'url': '/eula/'}, name='eula'),
    url(r'^login/$', views.login, name='blog_login'),
    url(r'^logout/$', views.logout, name='blog_logout'),
    url(r'^admin_page/$', views.admin_page, name='admin_page'),
    url(r'^lousy-login/$', views.lousy_login, name='lousy_login'),
    url(r'^lousy-secret/$', views.lousy_secret, name='lousy_secret'),
    url(r'^lousy-logout/$', views.lousy_logout, name='lousy_logout'),
    url(r'^save-session-data/$', views.save_session_data, name='save_session_data'),
    url(r'^access-session-data/$', views.access_session_data, name='access_session_data'),
    url(r'^delete-session-data/$', views.delete_session_data, name='delete_session_data'),
    url(r'^test-delete/$', views.test_delete, name='test_delete'),
    url(r'^test-session/$', views.test_session, name='test_session'),
    url(r'^stop-tracking/$', views.stop_tracking, name='stop_tracking'),
    url(r'^track_user/$', views.track_user, name='track_user'),
    url(r'^cookie/$', views.test_cookie, name='cookie'),
    url(r'^blog/$', views.test_redirect, name='test_redirect'),
    url(r'^$', views.post_list, name='post_list'),
]

django_project/cadmin/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^activate/account/$', views.activate_account, name='activate'),
    url(r'^register/$', views.register, name='register'),
    url(r'^password-change-done/$',
        auth_views.password_change_done,
        {'template_name': 'cadmin/password_change_done.html'},
        name='password_change_done'
        ),
    url(r'^password-change/$',
        auth_views.password_change,
        {'template_name': 'cadmin/password_change.html' , 'post_change_redirect': 'password_change_done'},
        name='password_change'
        ),
    url(r'^login/$', views.login, {'template_name': 'cadmin/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'cadmin/logout.html'}, name='logout'),
    url(r'^account-info/$', views.account_info, name='account_info'),

#----------------------------------------------------------------------------#
# If i remove these two views it gives me error what's wrong with these views
    url(r'^category/$', views.category_list, name='category_list'),
    url(r'^tag/$', views.tag_list, name='tag_list'),
# See them later  
#------------------------------------------------------------------------------#  
    url(r'^$', views.index, name='index'),
    url(r'^barcode/$', views.barcode, name='barcode'),
    url(r'^invoice/show/(?P<pk>[\d]+)/$', views.invoice_show, name='invoice_show'),
    url(r'^supplier/$', views.supplier_list, name='supplier_list'),
    url(r'^supplier/add/$', views.supplier_add, name='supplier_add'),
    url(r'^supplier/view/(?P<pk>[\d]+)/$', views.supplier_view, name='supplier_view'),
    url(r'^supplier/update/(?P<pk>[\d]+)/$', views.supplier_update, name='supplier_update'),
    url(r'^supplier/delete/(?P<pk>[\d]+)/$', views.supplier_delete, name='supplier_delete'),

    url(r'^supplier_ledger/$', views.supplier_ledger_list, name='supplier_ledger_list'),
    url(r'^supplier_ledger/add/$', views.supplier_ledger_add, name='supplier_ledger_add'),
    url(r'^supplier_ledger/update/(?P<pk>[\d]+)/$', views.supplier_ledger_update, name='supplier_ledger_update'),
    url(r'^supplier_ledger/delete/(?P<pk>[\d]+)/$', views.supplier_ledger_delete, name='supplier_ledger_delete'),

    url(r'^product/$', views.product_list, name='product_list'),
    url(r'^product/add/$', views.product_add, name='product_add'),
    # url(r'^purchase/product/add/$', views.purchase_product_add, name='purchase_product_add'),
    # url(r'^purchase/product/add/(?P<supplier>[\d]+)/$', views.purchase_product_add, name='purchase_product_add'),
    # url(r'^purchase/product/list/(?P<supplier>[\d]+)/$', views.purchase_product_list, name='purchase_product_list'),
    url(r'^product/view/$', views.product_view, name='product_view'),
    url(r'^product/update/(?P<pk>[\d]+)/$', views.product_update, name='product_update'),
    url(r'^product/delete/(?P<pk>[\d]+)/$', views.product_delete, name='product_delete'),

    url(r'^purchase/$', views.purchase_list, name='purchase_list'),
    url(r'^purchase/add/$', views.purchase_add, name='purchase_add'),
    url(r'^purchase/view/$', views.purchase_view, name='purchase_view'),
    url(r'^purchase/update/(?P<pk>[\d]+)/$', views.purchase_update, name='purchase_update'),
    url(r'^purchase/delete/(?P<pk>[\d]+)/$', views.purchase_delete, name='purchase_delete'),

    url(r'^customer/$', views.customer_list, name='customer_list'),
    url(r'^customer/add/$', views.customer_add, name='customer_add'),
    url(r'^customer/view/(?P<pk>[\d]+)/$', views.customer_view, name='customer_view'),
    url(r'^customer/update/(?P<pk>[\d]+)/$', views.customer_update, name='customer_update'),
    url(r'^customer/delete/(?P<pk>[\d]+)/$', views.customer_delete, name='customer_delete'),

    url(r'^sale/$', views.sale_list, name='sale_list'),
    url(r'^sale/add/$', views.sale_add, name='sale_add'),
    url(r'^sale/add1/$', views.sale_add1, name='sale_add1'),
    url(r'^search/$', views.search, name='search'),
    url(r'^sale/view/$', views.sale_view, name='sale_view'),
    url(r'^sale/update/(?P<pk>[\d]+)/$', views.sale_update, name='sale_update'),
    url(r'^sale/delete/(?P<pk>[\d]+)/$', views.sale_delete, name='sale_delete'),

    url(r'^customer_ledger/$', views.customer_ledger_list, name='customer_ledger_list'),
    url(r'^customer_ledger/add/$', views.customer_ledger_add, name='customer_ledger_add'),
    url(r'^customer_ledger/update/(?P<pk>[\d]+)/$', views.customer_ledger_update, name='customer_ledger_update'),
    url(r'^customer_ledger/delete/(?P<pk>[\d]+)/$', views.customer_ledger_delete, name='customer_ledger_delete'),
]

django_project/django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^cadmin/', include('cadmin.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import RegexValidator

# Create your models here.

class Author(models.Model):
    # required to associate Author model with User model (Important)
    user = models.OneToOneField(User, null=True, blank=True, on_delete = models.CASCADE)

    # additional fields
    activation_key = models.CharField(max_length=255, default=1)
    email_validated = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Supplier(models.Model):
    name = models.CharField(max_length=200)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    contact = models.CharField(validators=[phone_regex], max_length=17) # validators should be a list
    email = models.EmailField(max_length=200, blank=True)
    address = models.CharField(max_length=700)
    brandName = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    def __str__(self):
        return ("id: "+str(self.id)+": "+self.name) 

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Supplier, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('supplier_detail', args=[self.id, self.slug])

class Supplier_Ledger(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete = models.CASCADE)
    amount_paid = models.DecimalField(max_length=200, max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    # def __str__(self):
    #     return self.supplier

    def save(self, *args, **kwargs):
        self.slug = slugify(self.supplier)
        super(Supplier_Ledger, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('supplier_ledger_detail', args=[self.id, self.slug])   

class Purchase(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete = models.CASCADE)
    # product = models.ForeignKey(Product, on_delete = models.CASCADE)
    totalBill = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    discount = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    paidAmount = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    # balance = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)
 
    # @property
    # def balance(self):
    #     return -(self.totalBill - self.discount) + self.paidAmount

    # def __str__(self):
    #     return self.product

    # def get_readonly_fields(self, request, obj=None):
    #     if obj is None:
    #         return ['headline ']
    #     return []
  

    def save(self, *args, **kwargs):
        self.slug = slugify(self.supplier)
        super(Purchase, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('purchase_detail', args=[self.id, self.slug])

class Product(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete = models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200)
    # supplier = models.ForeignKey(Supplier, on_delete = models.CASCADE)
    description = models.CharField(max_length=5000, blank=True)
    fix_value = models.CharField(max_length=200, default= '2532')
    barcode = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    colour = models.CharField(max_length=200, blank=True)
    cost = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0)
    salePrice = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0)
    quantity = models.IntegerField(default = 0)
    bill = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    # class Meta:
    #     unique_together = ["name", "supplier", "description", "brand", "colour", "cost", "salePrice", "quantity"]

    # @property
    # def barcode(self):
    #     return (self.fix_value+str(self.id)+str(int(self.salePrice)))

    def barcode_generated(self, *args, **kwargs):
        self.barcode = self.fix_value+str(self.id)+str(int(self.salePrice))
        super(Product, self).save(*args, **kwargs)
        return self.barcode

    # def snippet(self):
    #     self.barcode = self.fix_value+str(self.id)+str(int(self.salePrice))
    #     return self.barcode    
    

    # @property
    # def bill(self):
    #     return self.quantity * self.cost 

    def __str__(self):
        return ("id: "+str(self.id)+": "+self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id, self.slug])          

class Customer(models.Model):
    name = models.CharField(max_length=200) 
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    contact = models.CharField(validators=[phone_regex], max_length=17) # validators should be a list
    email = models.EmailField(max_length=200, blank=True)
    address = models.CharField(max_length=700)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    def __str__(self):
        return ("id: "+str(self.id)+": "+self.name); 

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Customer, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('customer_detail', args=[self.id, self.slug])

class Sale(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    totalBill = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default=0.0)
    discount = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    receivedAmount = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    # balance = models.CharField(max_length=200, default=0)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    # @property
    # def balance(self):
    #     return -(self.totalBill - self.discount) + self.receivedAmount

    # def __str__(self):
    #     return self.product

    def save(self, *args, **kwargs):
        self.slug = slugify(self.customer)
        super(Sale, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('sale_detail', args=[self.id, self.slug])

class Sale_Product(models.Model):
    sale = models.ForeignKey(Sale, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    barcode = models.IntegerField()
    price = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default = 0.0)
    quantity = models.IntegerField(default = 0)
    bill = models.DecimalField(max_length=200, max_digits=15, decimal_places=2, default=0.0)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)        
          

class Customer_Ledger(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    amount_received = models.DecimalField(max_length=200, max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    def __str__(self):
        return self.customer

    def save(self, *args, **kwargs):
        self.slug = slugify(self.customer)
        super(Customer_Ledger, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('customer_ledger_detail', args=[self.id, self.slug])

class Invoice(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    def __str__(self):
        return self.customer

    def save(self, *args, **kwargs):
        self.slug = slugify(self.customer)
        super(Invoice, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('invoice_detail', args=[self.id, self.slug])                            


# from django.db import models
# from django.core.validators import RegexValidator

# # Create your models here.
# class Product(models.Model):
#     class Meta:
#         verbose_name_plural = "product"

#     product_id = models.CharField(primary_key=True,max_length=20)
#     product_name = models.CharField(max_length=200)
#     product_description = models.CharField(max_length=5000, blank=True)
#     product_barcode = models.CharField(max_length=200)
#     product_brand = models.CharField(max_length=200)
#     product_colour = models.CharField(max_length=200, blank=True)
#     product_cost = models.CharField(max_length=200)
#     product_salePrice = models.CharField(max_length=200)
#     product_quantity = models.CharField(max_length=200)
#     product_bill = models.CharField(max_length=200)
#     created_at = models.DateTimeField(auto_now_add =True)
#     updated_at = models.DateTimeField(auto_now =True)
#     def __str__(self):
#         return self.product_name
      

# class Purchase(models.Model):
#     class Meta:

django_project/cadmin/models.py
from django.db import models

# Create your models here.

django_project/cadmin/templates/cadmin/activated.html
{% extends "cadmin/base.html" %}

{% block title %}
    Create Account - {{ block.super }}
{% endblock %}

{% block content %}

    <div class="logout">
        <p>Account activated! Please <a href="{% url 'login' %}">login</a></p>
</div>

{% endblock %}

django_project/cadmin/templates/cadmin/customer_ledger_update.html
{% extends "cadmin/base_admin.html" %}

{% block title %}
Update  New Customer Ledger - {{ block.super }}
{% endblock %}

{% block main %}


<head><style>
#id_customer ,
#id_amount_received  {
      width: 100%;
    height: 100%;
    border: 1px solid #ccc;
}</style></head>

<div class="main">

    <!-- <p>&#187; <a href="{% url 'customer_ledger_list' %}">All Customer Ledgers</a> &#187; Update  Customer Ledger</p>

    <h3>Update  Customer Ledger</h3> -->

    

    <div class="page-wrapper">
        
        {% include "cadmin/header.html" %}
        <!-- start page container -->
        <div class="page-container">
             {% include "cadmin/sidebar.html" %}
            <!-- start page content -->
            <div class="page-content-wrapper">
                <div class="page-content">
                    <div class="page-bar">
                        <div class="page-title-breadcrumb">
                            <div class=" pull-left">
                                <div class="page-title">Dashboard</div>
                            </div>
                            <ol class="breadcrumb page-breadcrumb pull-right">
                                <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=#>Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                               <li><a class="parent-item" href="{% url 'customer_ledger_list' %}"> Customer Ledger</a>&nbsp;<i class="fa fa-angle-right"></i>
                                </li>
                                <li class="active">Update   Customer Ledger</li>
                            </ol>
                        </div>
                    </div>
                     
                   

                
                     <!-- start Payment Details -->
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="card card-box">
                                <div class="card-head">
                                    <header>Update  Customer Ledger</header>
                                    <button id = "panel-button2" 
                                           class = "mdl-button mdl-js-button mdl-button--icon pull-right" 
                                           data-upgraded = ",MaterialButton">
                                           <i class = "material-icons">more_vert</i>
                                        </button>
                                        <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                                           data-mdl-for = "panel-button2">
                                           <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                                           <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                                           <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                                        </ul>
                                </div>



                                                    <p>
                                                        {{ form.non_field_errors }}
                                                    </p>

                                <div class="card-body" id="bar-parent2">
                                    <form action="#" id="form_sample_2" class="form-horizontal" method="POST">
                                        <div class="form-body">
                                             {% csrf_token %}
                                             {{ form.media }}

                                             <div class="form-group row  margin-top-20">
                                                <label class="control-label col-md-3">Customer
                                                    <span class="required"> * </span>
                                                </label>
                                                <div class="col-md-4">
                                                    {{ form.customer.errors }}
                                                    {{ form.customer }}

                                                </div>
                                            </div>
                                            
                                           
                                            
                                             <div class="form-group row">
                                                <label class="control-label col-md-3">Amount Received
                                                    <span class="required"> * </span>
                                                </label>
                                                <div class="col-md-4">
                                                    {{ form.amount_received.errors }}
                                                    {{ form.amount_received }}
                                                </div>
                                            </div>
                                            
                                           
                                        
                                        </div>
                                         <div class="form-group">
                                            <div class="offset-md-3 col-md-9">
                                                <button type="submit" class="btn btn-info">Submit</button>
                                                <button type="button" class="btn btn-default">Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                                                       

</div>
{% endblock %}

django_project/cadmin/templates/cadmin/supplier_ledger_add.html
{% extends "cadmin/base_admin.html" %}

{% block title %}
Add New Supplier Ledger - {{ block.super }}
{% endblock %}

{% block main %}

<head><style>
#id_supplier ,
#id_amount_paid  {
      width: 100%;
    height: 100%;
    border: 1px solid #ccc;
}</style></head>

<div class="main">

    <!-- <p>&#187; <a href="{% url 'supplier_ledger_list' %}">All Supplier Ledgers</a> &#187; Add Supplier Ledger</p>

    <h3>Add Supplier Ledger</h3>
 -->
    

    <div class="page-wrapper">
        
        {% include "cadmin/header.html" %}
        <!-- start page container -->
        <div class="page-container">
             {% include "cadmin/sidebar.html" %}
            <!-- start page content -->
            <div class="page-content-wrapper">
                <div class="page-content">
                    <div class="page-bar">
                        <div class="page-title-breadcrumb">
                            <div class=" pull-left">
                                <div class="page-title">Dashboard</div>
                            </div>
                            <ol class="breadcrumb page-breadcrumb pull-right">
                                <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{% url 'index' %}">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                               <li><a class="parent-item" href="{% url 'supplier_ledger_list' %}">Supplier Ledger</a>&nbsp;<i class="fa fa-angle-right"></i>
                                </li>
                                <li class="active">Add Supplier Ledger</li>
                            </ol>
                        </div>
                    </div>
                     
                   

                
                     <!-- start Payment Details -->
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="card card-box">
                                <div class="card-head">
                                    <header>Add Supplier Ledger</header>
                                    <button id = "panel-button2" 
                                           class = "mdl-button mdl-js-button mdl-button--icon pull-right" 
                                           data-upgraded = ",MaterialButton">
                                           <i class = "material-icons">more_vert</i>
                                        </button>
                                        <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                                           data-mdl-for = "panel-button2">
                                           <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                                           <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                                           <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                                        </ul>
                                </div>


                                                            <p>
                                                                {{ form.non_field_errors }}
                                                            </p>

                                <div class="card-body" id="bar-parent2">
                                    <form action="#" id="form_sample_2" class="form-horizontal" method="POST">
                                        <div class="form-body">
                                             {% csrf_token %}
                                             {{ form.media }}

                                             <div class="form-group row  margin-top-20">
                                                <label class="control-label col-md-3">Supplier
                                                    <span class="required"> * </span>
                                                </label>
                                                <div class="col-md-4">
                                                   {{ form.supplier.errors }}
                                                   {{ form.supplier }}

                                                </div>
                                            </div>
                                             <div class="form-group row">
                                                <label class="control-label col-md-3">Amount paid
                                                    <span class="required"> * </span>
                                                </label>
                                                <div class="col-md-4">
                                                   {{ form.amount_paid.errors }}
                                                   {{ form.amount_paid }}
                                                       
                                                    </div>
                                                </div>
                                            </div>
                                            
                                           
                                        
                                        </div>
                                         <div class="form-group">
                                            <div class="offset-md-3 col-md-9">
                                                <button type="submit" class="btn btn-info">Submit</button>
                                                <button type="button" class="btn btn-default" onclick="window.location.href='{% url 'supplier_ledger_list' %}'">Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

</div>
{% endblock %}

django_project/cadmin/templates/cadmin/tag_add.html
{% extends "cadmin/base_admin.html" %}

{% block title %}
    Add New Tag - {{ block.super }}
{% endblock %}

{% block main %}

    <div class="main">

        <p>&#187; <a href="{% url 'tag_list' %}">All Tags</a> &#187; Add Tag</p>

        <h3>Add Tag</h3>

        {% if messages %}
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        {% endif %}

        {{ form.non_field_errors }}

        <form action="" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.name.label_tag }}</td>
                    <td>
                        {{ form.name.errors }}
                        {{ form.name }}
                    </td>
                </tr>
                <tr>
                    <td>{{ form.slug.label_tag }}</td>
                    <td>
                        {{ form.slug.errors }}
                        {{ form.slug }}
                    </td>
                </tr>

                {% if request.user.is_superuser %}
                    <tr>
                        <td>{{ form.author.label_tag }}</td>
                        <td>
                            {{ form.author.errors }}
                            {{ form.author }}
                        </td>
                    </tr>
                {% endif %}

                <tr>
                    <td></td>
                    <td><input type="submit" value="Add Tag"></td>
                </tr>
            </table>
        </form>

    </div>

{% endblock %}